#!/bin/bash

if [ ! -f "lem-in" ]
then
	echo "Couldn't run script: lem-in executable not found."
	exit 1
fi
src=$(wc -l $1 | cut -d ' ' -f1)
lem=$(./lem-in < $1)
res=$(echo "$lem" | wc -l)
line=$(($res - $src -1))
echo "$lem"
echo Here is the number of lines returned: $line
end=$(tail -1 $1 | cut -d '#' -f2)
test=$(tail -1 $1 | cut -d ' ' -f1)
generator="#Here"
if [ "$test" == "$generator" ]
then
	echo $end
fi
